const strings =   {
  Add:`Add`,
  AddComment:`Add Comment`,
  Admin: 'Admin',
  Administration: 'Administration',
  Allowed:`Allowed`,
  Apply:`Apply`,
  appTitle:`Team Calendar`,
  asc:`Ascending`,
  Cancel:`Cancel`,
  CannotAddPersonal:`You do not have enough remaining personal time.`,
  CannotAddVacation:`You do not have enough remaining vacation time.`,
  Clear:`Clear`,
  Click:`Click`,
  Close:`Close`,
  Comment:`Comment`,
  ConfirmDeleteTeam:`Are you sure you want to remove the entire '{0}' team?`,
  ConfirmDeleteTeamMember:`Are you sure you want to remove team member '{0}' from the '{1}' team`,
  Count: '{0} {1}',
  Country: 'Country',
  Dark:`Dark`,
  DefaultSort:`Default sort`,
  DefaultTab:`Default tab`,
  defaultteams:`Default Teams`,
  Delete:`Delete`,
  DeleteCommentAsWell:`Would you also like to clear the comment for this day?`,
  DeleteUser:`Are you sure you want to delete '{0}'?`,
  desc:`Decending`,
  DirectReports: 'Direct Reports',
  Done:`Done`,
  Download: 'Download',
  DownloadToCSV: 'Download current table data to CSV',
  Edit:`Edit`,
  EditComment:`Edit Comment: {0}`,
  EmailAddress: 'Email Address',
  Filter:`Filter`,
  FilterByTeams:`Filter by teams`,
  FontSizeDecrease: 'Decrease font size',
  FontSizeIncrease: 'Increase font size',
  Global:`Global`,
  GoToToday:`Go to today`,
  Hide: 'Hide',
  HoldShift: `Hold shift to add a new line.`,
  Holiday:`Holiday`,
  HolidayDecorations:`Holiday Decorations`,
  HolidayLocale: `Holiday Locale`,
  Hover:`Hover`,
  HoverToFlip:`Flip`,
  invalidDuplicate: 'No duplicate {0}s allowed.',
  invalidNoValue: 'Value is required.',
  invalidMin: 'Minimum is {0}.',
  invalidMax: 'Maximum is {0}.',
  invalidTooShort: '{0} character minimum.',
  InvalidRowData: 'Invalid row data',
  invalidUser: 'User {0} has not been onboarded. Please contact your manager for assistance.',
  invalidUserNameEMail: 'Invalid username / email.',
  Layout:`Layout`,
  Light:`Light`,
  Loading:`Loading`,
  Logout:`Sign out`,
  Manager:`Manager`,
  MaskMyData:`Mask my data for other users`,
  Masked:`Private`,
  MinumumLength:`Items must be at least 5 characters`,
  Month:`Month`,
  MyTotals:`My Totals`,
  MustCancelEdit: 'Apply or Cancel edits to proceed.',
  Name:`Name`,
  New:`New`,
  No:`No`,
  NoDuplicates:`Item already exists`,
  NoRows:`There are no rows that match your search criteria. Please adjust your search.`,
  None:`None`,
  OK:`OK`,
  Or:`Or`,
  Organization:`Organization`,
  Other:`Other`,
  P:`P`,
  People: 'People',
  Personal:`Personal`,
  PersonalAM:`Morning personal`,
  PersonalAllowed:`Personal days allowed`,
  PersonalDaysRemaining:`Personal days remaining`,
  PersonalPM:`Afternoon personal`,
  Preferences:`Preferences for {0}`,
  Print: 'Print',
  Remaining:`Remaining`,
  Remove: 'Remove',
  RemoveSort: 'Remove sort',
  Search:`Search {0}`,
  SelectDefaultTeams:`Select default search teams`,
  SelectTeam:`Select team`,
  SelectTeamMembers:`Select team members`,
  SetAsDefaultTab:`Set as default tab`,
  Show: 'Show',
  ShowUserYear: 'Show full year for {0}',
  Sick:`Sick`,
  Sort:`Sort`,
  SortAction: 'Sort {0} {1}',
  SortBy: 'Sort by {0}',
  Sorted:`Sorted`,
  TeamMembers:`Team Members`,
  Team:`Team`,
  TeamAdmin:`Team Administration`,
  Teams: 'Teams',
  Theme:`Theme`,
  ThisYear:`This Year`,
  TimeOffTypes:`Time Off Types`,
  Today:`Today`,
  Unsorted: '{0} - Unsorted',
  UsedAll:`You have sheduled or used all available {0} time.`,
  Username: 'Username',
  V:`V`,
  Vacation:`Vacation`,
  VacationAM:`Morning vacation`,
  VacationAllowed:`Vacation days allowed`,
  VacationDaysRemaining:`Vacation days remaining`,
  VacationPM:`Afternoon vacation`,
  ViewComment:`View Comment: {0}`,
  Year:`Year`,
  Yes:`Yes`
};

export default strings;
