const teamsFromDB = {
  "ragusa-reports": {
    owner: "bragusa@us.ibm.com",
    members: [
      "tom.rontiris@us.ibm.com",
      "bakkired@in.ibm.com",
      "ogdent@us.ibm.com",
      "Ari.Geller@ibm.com",
      "enterlin@us.ibm.com",
      "Kaila.Lopez-Sirvent@ibm.com",
      "kristinf@us.ibm.com",
      "meshack.chintagunta@in.ibm.com",
      "Rohit.Chauda@ibm.com",
      "Anjali.Chauhan2@ibm.com",
      "abpaul24@in.ibm.com",
      "aqib.mirza@ibm.com",
      "vbhatra@us.ibm.com",
      "cgirani@br.ibm.com",
      "hectord@br.ibm.com",
    ],
  },
  "emerson-reports": {
    owner: "kemerson@us.ibm.com",
    members: [
      "bragusa@us.ibm.com",
      "ltekatsc@br.ibm.com",
      "mdickens@us.ibm.com",
      "rpdias@br.ibm.com",
      "shauptma@us.ibm.com",
      "zhengy@us.ibm.com",
    ],
  },
  "crispin-reports": {
    owner: "mcrispin@us.ibm.com",
    members: [
      "mlalgaza@us.ibm.com",
      "kadamdas@in.ibm.com",
      "kevin_doust@uk.ibm.com",
      "slai@us.ibm.com",
      "roberta.magueta@br.ibm.com",
      "tessa.olson@uk.ibm.com",
      "manishsaki@in.ibm.com",
    ],
  },
  "brockway-managers": {
    owner: "brockway@us.ibm.com",
    members: [
      "kemerson@us.ibm.com",
      "mcrispin@us.ibm.com",
      "kadamdas@in.ibm.com",
      "bragusa@us.ibm.com",
      "ltekatsc@br.ibm.com",
      "mdickens@us.ibm.com",
      "roberta.magueta@br.ibm.com",
      "kevin_doust@uk.ibm.com",
      "rpdias@br.ibm.com",
      "manishsaki@in.ibm.com",
    ],
  },
  "brockway-reports": {
    owner: "brockway@us.ibm.com",
    members: [
      "jennyw@us.ibm.com",
      "kemerson@us.ibm.com",
      "mcaissey@us.ibm.com",
      "msielian@us.ibm.com",
      "peter_niblett@uk.ibm.com",
      "sls@ca.ibm.com",
      "abhattacharyya@us.ibm.com",
      "mcrispin@us.ibm.com",
    ],
  },
  "das-reports": {
    owner: "kadamdas@in.ibm.com",
    members: [
      "alexandre.quinteiro@br.ibm.com",
      "amitmangalvedkar@in.ibm.com",
      "aadawadk@in.ibm.com",
      "andrercm@br.ibm.com",
      "Arun.Narayanan2@ibm.com",
      "Ashish.Mahawal1@ibm.com",
      "abensal@us.ibm.com",
      "caroazadze@ibm.com",
      "nataraj.s@in.ibm.com",
      "pakosal1@in.ibm.com",
      "ypkim@us.ibm.com",
      "acree@us.ibm.com",
      "svalluri@in.ibm.com",
      "shajsyed@in.ibm.com",
    ],
  },
  "tekatscz-reports": {
    owner: "ltekatsc@br.ibm.com",
    members: [
      "bzhu@ca.ibm.com",
      "ckao@us.ibm.com",
      "Eric Klingelberger",
      "Hari.Palleti@ibm.com",
      "karolsn@br.ibm.com",
      "lokesh.sreedhara@us.ibm.com",
      "marcblec@br.ibm.com",
      "marcof@br.ibm.com",
      "Matheus.Cardoso@ibm.com",
      "quinnt@us.ibm.com",
      "twhart@us.ibm.com",
    ],
  },
  "doust-reports": {
    owner: "kevin_doust@uk.ibm.com",
    members: [
      "beatriz.castro@ibm.com",
      "xchenhui@cn.ibm.com",
      "ecliff@us.ibm.com",
      "luje@us.ibm.com",
      "Jonah.Luckett@ibm.com",
      "LEVELL@uk.ibm.com",
      "lebm@br.ibm.com",
      "rborto@br.ibm.com",
      "sanjay.prabhakar@uk.ibm.com",
      "Suraj Tiwari",
      "maotsh@cn.ibm.com",
    ],
  },
  "saki-reports": {
    owner: "manishsaki@in.ibm.com",
    members: [
      "Claire.Jenkins@ibm.com",
      "Kunal.Kenge@ibm.com",
      "Srini Badari",
      "swingate@ibm.com",
      "SBUBE@de.ibm.com",
      "Vinit.Kumar3@ibm.com",
      "YASH.YADAV@ibm.com",
    ],
  },
  "dickenson-reports": {
    owner: "mdickens@us.ibm.com",
    members: [
      "anahas@br.ibm.com",
      "WHITFIEA@uk.ibm.com",
      "Atul.Srivastav@ibm.com",
      "BAKOWSKI@uk.ibm.com",
      "cochran@ibm.com",
      "Daniel.Istrate1@ibm.com",
      "PARKERDA@uk.ibm.com",
      "elyb@br.ibm.com",
      "IANBODEN@uk.ibm.com",
      "STONEPD@uk.ibm.com",
      "Rawa.Resul@ibm.com",
      "sachin.balagopalan@us.ibm.com",
      "sbudhira@us.ibm.com",
      "KLAPITOM@uk.ibm.com",
      "Vishal.Patel7@ibm.com",
    ],
  },
  "dias-reports": {
    owner: "rpdias@br.ibm.com",
    members: [
      "awills@us.ibm.com",
      "mccafferty@us.ibm.com",
      "ankits@ibm.com",
      "ashlesha.potdar@in.ibm.com",
      "bdozorts@us.ibm.com",
      "briangar@us.ibm.com",
      "creyes@us.ibm.com",
      "rodas@ca.ibm.com",
      "jgydus@us.ibm.com",
      "pete.halbeisen@us.ibm.com",
      "Prakruti.Shah@ibm.com",
      "Rajan Chaudhary",
      "sboudrea@us.ibm.com",
      "Subrat Mishra",
      "Unnati.Solanki@ibm.com",
      "xinyuwu@us.ibm.com",
    ],
  },
  "costa-reports": {
    owner: "roberta.magueta@br.ibm.com",
    members: [
      "athakur@us.ibm.com",
      "andrefgj@br.ibm.com",
      "dkioshi@ibm.com",
      "danilol@br.ibm.com",
      "febergamo@ibm.com",
      "igortn@ibm.com",
      "IANDREI2@ie.ibm.com",
      "jeancrg@br.ibm.com",
      "lyoshida@br.ibm.com",
      "luisfelipe@ibm.com",
      "luiz.lucena@ibm.com",
      "MITTENMA@ie.ibm.com",
      "mraikhli@us.ibm.com",
      "naraujos@br.ibm.com",
      "PANPANLI@ie.ibm.com",
      "qmao@us.ibm.com",
      "Sujala.Velagapudi@ibm.com",
      "yann.casanova@ibm.com",
      "jiayybj@cn.ibm.com",
    ],
  },
  others: {
    owner: "bragusa@us.ibm.com",
    members: [
      "alex.donatelli@it.ibm.com",
      "yinzhu@ca.ibm.com",
      "elibow@us.ibm.com",
      "psolfa@br.ibm.com",
      "arlindo@us.ibm.com",
    ],
  },
};

const usersTimeOffDataFromDB = [
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "pakosal1@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 30, personal: 0 } } },
    username: "sbudhira@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "febergamo@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "slai@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "ogdent@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 3 } } },
    username: "Kaila.Lopez-Sirvent@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "rodas@ca.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "pete.halbeisen@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "shauptma@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "yinzhu@ca.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "Daniel.Istrate1@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "awills@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Subrat Mishra",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "jiayybj@cn.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Sujala.Velagapudi@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "amitmangalvedkar@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "alexandre.quinteiro@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "athakur@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "aadawadk@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "YASH.YADAV@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "ypkim@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "PARKERDA@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "aqib.mirza@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "lyoshida@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "igortn@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "kristinf@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 22, personal: 0 } } },
    username: "elyb@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Vinit.Kumar3@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 0 } } },
    username: "Vishal.Patel7@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "ankits@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Anjali.Chauhan2@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 15, personal: 4 } } },
    username: "WHITFIEA@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "elibow@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "naraujos@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "alex.donatelli@it.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "jgydus@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 26, personal: 0 } } },
    username: "Ashish.Mahawal1@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "bakkired@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "andrercm@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "sboudrea@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "abensal@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 20, personal: 0 } } },
    username: "nataraj.s@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 30, personal: 0 } } },
    username: "Leo.Davison@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "andrefgj@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "sanjay.prabhakar@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "cochran@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 0 } } },
    username: "danilol@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "IANDREI2@ie.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "svalluri@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "yann.casanova@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 22, personal: 0 } } },
    username: "meshack.chintagunta@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "anahas@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "arlindo@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "SBUBE@de.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "tessa.olson@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "shajsyed@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "mccafferty@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "enterlin@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "jeancrg@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Kunal.Kenge@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Atul.Srivastav@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Rohit.Chauda@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Rajan Chaudhary",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "PANPANLI@ie.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 22, personal: 1 } } },
    username: "Arun.Narayanan2@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "Ari.Geller@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Hari.Palleti@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "cgirani@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Matheus.Cardoso@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Eric Klingelberger",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "luiz.lucena@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "luisfelipe@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "qmao@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "hectord@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "twhart@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "caroazadze@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Claire.Jenkins@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "vbhatra@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "KLAPITOM@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "briangar@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "bzhu@ca.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "acree@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "karolsn@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 22, personal: 0 } } },
    username: "IANBODEN@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "quinnt@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "ckao@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "mlalgaza@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "mraikhli@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "zhengy@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "swingate@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "lokesh.sreedhara@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "ashlesha.potdar@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 0 } } },
    username: "luje@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Rawa.Resul@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "beatriz.castro@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "STONEPD@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Jonah.Luckett@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 30, personal: 0 } } },
    username: "maotsh@cn.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "marcof@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "xchenhui@cn.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Srini Badari",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 0 } } },
    username: "dkioshi@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 0 } } },
    username: "xinyuwu@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "marcblec@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 22, personal: 0 } } },
    username: "BAKOWSKI@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "Unnati.Solanki@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "rborto@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "Prakruti.Shah@ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "ecliff@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "psolfa@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "LEVELL@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "Suraj Tiwari",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "creyes@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "MITTENMA@ie.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "sachin.balagopalan@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "bdozorts@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "lebm@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "abhattacharyya@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "jennyw@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "mcaissey@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "msielian@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "peter_niblett@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 3 } } },
    username: "sls@ca.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "abpaul24@in.ibm.com",
  },
  {
    years: {
      2023: {
        comments: {
          "11-22": "this is a test comment",
          "11-23": "this is another a test comment",
        },
        timeoff: {
          "1-2": "H",
          "1-16": "H",
          "1-27": "P",
          "3-17": "P",
          "3-20": "P",
          "4-24": "V",
          "5-24": "V",
          "5-29": "H",
          "6-5": "VP",
          "6-6": "VA",
          "6-16": "V",
          "7-3": "V",
          "7-4": "H",
          "7-27": "V",
          "7-28": "V",
          "7-31": "V",
          "8-4": "V",
          "8-21": "V",
          "8-22": "V",
          "8-23": "V",
          "8-24": "V",
          "8-25": "P",
          "8-28": "V",
          "9-4": "H",
          "10-11": "S",
          "10-12": "S",
          "10-13": "S",
          "10-16": "S",
          "11-22": "V",
          "11-23": "H",
          "11-24": "H",
          "12-25": "H",
        },
        totals: { vacation: 25, personal: 4 },
      },
    },
    username: "mcrispin@us.ibm.com",
  },
  {
    years: {
      2023: {
        comments: {
          "2-28": "Colonoscopy",
          "5-26": "Early Memorial Day (Afternoon)",
        },
        timeoff: {
          "2-23": "VP",
          "2-28": "O",
          "3-6": "P",
          "3-20": "VP",
          "3-23": "P",
          "3-24": "P",
          "3-27": "P",
          "3-28": "V",
          "5-8": "V",
          "5-9": "V",
          "5-10": "V",
          "5-11": "V",
          "5-12": "V",
          "5-26": "O",
          "6-21": "V",
          "7-3": "V",
          "7-14": "V",
          "7-17": "V",
          "7-18": "V",
          "7-19": "V",
          "7-20": "V",
          "7-21": "V",
          "11-10": "V",
          "11-22": "V",
          "11-23": "H",
          "11-24": "H",
          "12-20": "V",
          "12-21": "V",
          "12-22": "V",
          "12-25": "H",
          "12-26": "V",
          "12-27": "V",
          "12-28": "V",
          "12-29": "V",
        },
        totals: { vacation: 0, personal: 0 },
      },
    },
    username: "tom.rontiris@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "kadamdas@in.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 25, personal: 4 } } },
    username: "kemerson@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "brockway@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "kevin_doust@uk.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "roberta.magueta@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "ltekatsc@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "bragusa@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 15, personal: 4 } } },
    username: "rpdias@br.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "mdickens@us.ibm.com",
  },
  {
    years: { 2023: { timeoff: {}, totals: { vacation: 0, personal: 0 } } },
    username: "manishsaki@in.ibm.com",
  },
];

const usersFromDB = {
  "mdickens@us.ibm.com": {
    username: "mdickens@us.ibm.com",
    name: "Marc Dickenson",
    manager: "Katherine Emerson",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "kadamdas@in.ibm.com": {
    username: "kadamdas@in.ibm.com",
    name: "Kadambari Das",
    manager: "Michael Crispin",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "roberta.magueta@br.ibm.com": {
    username: "roberta.magueta@br.ibm.com",
    name: "Roberta Magueta Costa",
    manager: "Michael Crispin",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "mcrispin@us.ibm.com": {
    username: "mcrispin@us.ibm.com",
    name: "Michael Crispin",
    manager: "Brandon Brockway",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 25, personal: 4 },
    preferences: {
      theme: "light",
      hovertoflip: true,
      yearlayout: "3:4",
      mask: true,
      defaultteams: ["crispin-reports"],
    },
  },
  "kemerson@us.ibm.com": {
    username: "kemerson@us.ibm.com",
    name: "Katherine Emerson",
    manager: "Brandon Brockway",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "brockway@us.ibm.com": {
    username: "brockway@us.ibm.com",
    name: "Brandon Brockway",
    manager: "Suzanne Livingston",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "kevin_doust@uk.ibm.com": {
    username: "kevin_doust@uk.ibm.com",
    name: "Kevin Doust",
    manager: "Michael Crispin",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "ltekatsc@br.ibm.com": {
    username: "ltekatsc@br.ibm.com",
    name: "Leonardo Tekatscz",
    manager: "Katherine Emerson",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "bragusa@us.ibm.com": {
    username: "bragusa@us.ibm.com",
    name: "Brian Ragusa",
    manager: "Katherine Emerson",
    isadmin: false,
    ismanager: true,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: {
      theme: "light",
      hovertoflip: true,
      yearlayout: "3:4",
      defaultteams: ["ragusa-reports"],
    },
  },
  "manishsaki@in.ibm.com": {
    username: "manishsaki@in.ibm.com",
    name: "Manish Saki",
    manager: "Michael Crispin",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "rpdias@br.ibm.com": {
    username: "rpdias@br.ibm.com",
    name: "Ricardo de Paula Dias",
    manager: "Katherine Emerson",
    ismanager: true,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "pakosal1@in.ibm.com": {
    username: "pakosal1@in.ibm.com",
    name: "Padmanabhan Kosalaram",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "sbudhira@us.ibm.com": {
    username: "sbudhira@us.ibm.com",
    name: "Sarika Budhiraja",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "febergamo@ibm.com": {
    username: "febergamo@ibm.com",
    name: "Fernanda Bergamo",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "slai@us.ibm.com": {
    username: "slai@us.ibm.com",
    name: "Su-Kuei Lai",
    ismanager: false,
    isadmin: false,
    manager: "Michael Crispin",
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "ogdent@us.ibm.com": {
    username: "ogdent@us.ibm.com",
    name: "Thomas Ogden",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Kaila.Lopez-Sirvent@ibm.com": {
    username: "Kaila.Lopez-Sirvent@ibm.com",
    name: "Kaila Sirvent",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "rodas@ca.ibm.com": {
    username: "rodas@ca.ibm.com",
    name: "Clarissa Vukovic",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "pete.halbeisen@us.ibm.com": {
    username: "pete.halbeisen@us.ibm.com",
    name: "Pete Halbeisen",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "shauptma@us.ibm.com": {
    username: "shauptma@us.ibm.com",
    name: "Steve Hauptman",
    manager: "Katherine Emerson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "yinzhu@ca.ibm.com": {
    username: "yinzhu@ca.ibm.com",
    name: "Yin Zhu",
    manager: "Ana Villarreal",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Daniel.Istrate1@ibm.com": {
    username: "Daniel.Istrate1@ibm.com",
    name: "Daniel Istrate",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "awills@us.ibm.com": {
    username: "awills@us.ibm.com",
    name: "Andrea Wills",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Subrat Mishra": {
    username: "Subrat Mishra",
    name: "Subrat Mishra",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "jiayybj@cn.ibm.com": {
    username: "jiayybj@cn.ibm.com",
    name: "Yuan Yuan Jia",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Sujala.Velagapudi@ibm.com": {
    username: "Sujala.Velagapudi@ibm.com",
    name: "Sujala Velagapudi",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "amitmangalvedkar@in.ibm.com": {
    username: "amitmangalvedkar@in.ibm.com",
    name: "Amit Mangalvedkar",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "alexandre.quinteiro@br.ibm.com": {
    username: "alexandre.quinteiro@br.ibm.com",
    name: "Alexandre Fernandes Quinteiro",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "athakur@us.ibm.com": {
    username: "athakur@us.ibm.com",
    name: "Aman Thakur",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "aadawadk@in.ibm.com": {
    username: "aadawadk@in.ibm.com",
    name: "Amrin Maria R. Khan Adawadkar",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "YASH.YADAV@ibm.com": {
    username: "YASH.YADAV@ibm.com",
    name: "Yash Yadav",
    manager: "Manish Saki",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "ypkim@us.ibm.com": {
    username: "ypkim@us.ibm.com",
    name: "Phil Kim",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "PARKERDA@uk.ibm.com": {
    username: "PARKERDA@uk.ibm.com",
    name: "David Parker",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "aqib.mirza@ibm.com": {
    username: "aqib.mirza@ibm.com",
    name: "Aqib Mirza",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "lyoshida@br.ibm.com": {
    username: "lyoshida@br.ibm.com",
    name: "Leandro Yoshida",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "igortn@ibm.com": {
    username: "igortn@ibm.com",
    name: "Igor Nietmann",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "kristinf@us.ibm.com": {
    username: "kristinf@us.ibm.com",
    name: "Kristin M Fernandes",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "elyb@br.ibm.com": {
    username: "elyb@br.ibm.com",
    name: "Ely De Azevedo Barros",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Vinit.Kumar3@ibm.com": {
    username: "Vinit.Kumar3@ibm.com",
    name: "Vinit Kumar",
    manager: "Manish Saki",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Vishal.Patel7@ibm.com": {
    username: "Vishal.Patel7@ibm.com",
    name: "Vishal Patel",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "ankits@ibm.com": {
    username: "ankits@ibm.com",
    name: "Ankit Shah",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Anjali.Chauhan2@ibm.com": {
    username: "Anjali.Chauhan2@ibm.com",
    name: "Anjali Chauhan",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "WHITFIEA@uk.ibm.com": {
    username: "WHITFIEA@uk.ibm.com",
    name: "Andrew Whitfield",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "elibow@us.ibm.com": {
    username: "elibow@us.ibm.com",
    name: "Eric B. Libow",
    manager: "Suzanne Livingston",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "naraujos@br.ibm.com": {
    username: "naraujos@br.ibm.com",
    name: "Natalia Araujo",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "alex.donatelli@it.ibm.com": {
    username: "alex.donatelli@it.ibm.com",
    name: "Alex Donatelli",
    manager: "Suzanne Livingston",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "jgydus@us.ibm.com": {
    username: "jgydus@us.ibm.com",
    name: "Joseph Gydus",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Ashish.Mahawal1@ibm.com": {
    username: "Ashish.Mahawal1@ibm.com",
    name: "Ashish Mahawal",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "bakkired@in.ibm.com": {
    username: "bakkired@in.ibm.com",
    name: "Jaanvi Akkireddi",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "andrercm@br.ibm.com": {
    username: "andrercm@br.ibm.com",
    name: "Andre Ricardo De Campos Marcelino",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "sboudrea@us.ibm.com": {
    username: "sboudrea@us.ibm.com",
    name: "Scott Boudreau",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "abensal@us.ibm.com": {
    username: "abensal@us.ibm.com",
    name: "Aymen Ben Salah",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "nataraj.s@in.ibm.com": {
    username: "nataraj.s@in.ibm.com",
    name: "Nataraj Shivashankaraiah",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Leo.Davison@uk.ibm.com": {
    username: "Leo.Davison@uk.ibm.com",
    name: "Leo Davison",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "andrefgj@br.ibm.com": {
    username: "andrefgj@br.ibm.com",
    name: "Andre Ferreira",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "sanjay.prabhakar@uk.ibm.com": {
    username: "sanjay.prabhakar@uk.ibm.com",
    name: "Sanjay Prabhakar",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "cochran@ibm.com": {
    username: "cochran@ibm.com",
    name: "Christopher Cochran",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "danilol@br.ibm.com": {
    username: "danilol@br.ibm.com",
    name: "Danilo Lopes",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "IANDREI2@ie.ibm.com": {
    username: "IANDREI2@ie.ibm.com",
    name: "Ionut Andrei",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "svalluri@in.ibm.com": {
    username: "svalluri@in.ibm.com",
    name: "Sekhar Valluri",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "yann.casanova@ibm.com": {
    username: "yann.casanova@ibm.com",
    name: "Yann Casanova",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "meshack.chintagunta@in.ibm.com": {
    username: "meshack.chintagunta@in.ibm.com",
    name: "Meshack Chintagunta",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "anahas@br.ibm.com": {
    username: "anahas@br.ibm.com",
    name: "Alice Nahas da Silva",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "arlindo@us.ibm.com": {
    username: "arlindo@us.ibm.com",
    name: "Arlindo Chiavegatto",
    manager: "Brandon Brockway",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "SBUBE@de.ibm.com": {
    username: "SBUBE@de.ibm.com",
    name: "Sören Bube",
    manager: "Manish Saki",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "tessa.olson@uk.ibm.com": {
    username: "tessa.olson@uk.ibm.com",
    name: "Tessa Olson",
    manager: "Michael Crispin",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "shajsyed@in.ibm.com": {
    username: "shajsyed@in.ibm.com",
    name: "Shajeena Syed",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "mccafferty@us.ibm.com": {
    username: "mccafferty@us.ibm.com",
    name: "Angela McCafferty",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "enterlin@us.ibm.com": {
    username: "enterlin@us.ibm.com",
    name: "Christy Enterline",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "jeancrg@br.ibm.com": {
    username: "jeancrg@br.ibm.com",
    name: "Jean Gonçalves",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Kunal.Kenge@ibm.com": {
    username: "Kunal.Kenge@ibm.com",
    name: "Kunal Kenge",
    manager: "Manish Saki",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Atul.Srivastav@ibm.com": {
    username: "Atul.Srivastav@ibm.com",
    name: "Atul Srivastev",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Rohit.Chauda@ibm.com": {
    username: "Rohit.Chauda@ibm.com",
    name: "Rohit Chauda",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Rajan Chaudhary": {
    username: "Rajan Chaudhary",
    name: "Rajan Chaudhary",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "PANPANLI@ie.ibm.com": {
    username: "PANPANLI@ie.ibm.com",
    name: "Panpan Lin",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Arun.Narayanan2@ibm.com": {
    username: "Arun.Narayanan2@ibm.com",
    name: "Arun Narayanan",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Ari.Geller@ibm.com": {
    username: "Ari.Geller@ibm.com",
    name: "Ari Geller",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Hari.Palleti@ibm.com": {
    username: "Hari.Palleti@ibm.com",
    name: "Hari Palleti",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "cgirani@br.ibm.com": {
    username: "cgirani@br.ibm.com",
    name: "Claudia Regina Girani Tejos",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Matheus.Cardoso@ibm.com": {
    username: "Matheus.Cardoso@ibm.com",
    name: "Matheus Cardoso de Medeiros",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Eric Klingelberger": {
    username: "Eric Klingelberger",
    name: "Eric Klingelberger",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "luiz.lucena@ibm.com": {
    username: "luiz.lucena@ibm.com",
    name: "Luiz Gustavo Lucena",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "luisfelipe@ibm.com": {
    username: "luisfelipe@ibm.com",
    name: "Luis Silva",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "qmao@us.ibm.com": {
    username: "qmao@us.ibm.com",
    name: "Qiuping Mao",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "hectord@br.ibm.com": {
    username: "hectord@br.ibm.com",
    name: "Hector Davis",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "twhart@us.ibm.com": {
    username: "twhart@us.ibm.com",
    name: "Tremaine Hart",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "caroazadze@ibm.com": {
    username: "caroazadze@ibm.com",
    name: "Caroline E Azadze",
    manager: "marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Claire.Jenkins@ibm.com": {
    username: "Claire.Jenkins@ibm.com",
    name: "Claire Jenkins",
    manager: "Manish Saki",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "vbhatra@us.ibm.com": {
    username: "vbhatra@us.ibm.com",
    name: "Vidad Bhatra",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "KLAPITOM@uk.ibm.com": {
    username: "KLAPITOM@uk.ibm.com",
    name: "Tom Klapiscak",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "briangar@us.ibm.com": {
    username: "briangar@us.ibm.com",
    name: "Brian Garrett",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "bzhu@ca.ibm.com": {
    username: "bzhu@ca.ibm.com",
    name: "Brian Zhu",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "acree@us.ibm.com": {
    username: "acree@us.ibm.com",
    name: "Rick Acree",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "karolsn@br.ibm.com": {
    username: "karolsn@br.ibm.com",
    name: "Joao Paulo Karol Santos Nunes",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "IANBODEN@uk.ibm.com": {
    username: "IANBODEN@uk.ibm.com",
    name: "Ian Boden",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "quinnt@us.ibm.com": {
    username: "quinnt@us.ibm.com",
    name: "Terence J. Quinn",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "ckao@us.ibm.com": {
    username: "ckao@us.ibm.com",
    name: "Conrad Kao",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "mlalgaza@us.ibm.com": {
    username: "mlalgaza@us.ibm.com",
    name: "Magdy Labib Al-Gazaz",
    manager: "Michael Crispin",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "mraikhli@us.ibm.com": {
    username: "mraikhli@us.ibm.com",
    name: "Mikhail Raikhline",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "zhengy@us.ibm.com": {
    username: "zhengy@us.ibm.com",
    name: "Yajin Zheng",
    manager: "Katherine Emerson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "swingate@ibm.com": {
    username: "swingate@ibm.com",
    name: "Steven Wingate",
    manager: "Manish Saki",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "lokesh.sreedhara@us.ibm.com": {
    username: "lokesh.sreedhara@us.ibm.com",
    name: "Lokesh Sreedhara",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "ashlesha.potdar@in.ibm.com": {
    username: "ashlesha.potdar@in.ibm.com",
    name: "Ashlesha Mhashelkar",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "luje@us.ibm.com": {
    username: "luje@us.ibm.com",
    name: "Jennifer Lu",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Rawa.Resul@ibm.com": {
    username: "Rawa.Resul@ibm.com",
    name: "Rawa Resul",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "beatriz.castro@ibm.com": {
    username: "beatriz.castro@ibm.com",
    name: "Beatriz Falcão Castro",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "STONEPD@uk.ibm.com": {
    username: "STONEPD@uk.ibm.com",
    name: "Paul Stone",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Jonah.Luckett@ibm.com": {
    username: "Jonah.Luckett@ibm.com",
    name: "Jonah Luckett",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "maotsh@cn.ibm.com": {
    username: "maotsh@cn.ibm.com",
    name: "Ting Mao",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "marcof@br.ibm.com": {
    username: "marcof@br.ibm.com",
    name: "Marco Antonio Ferreira De Araujo",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "xchenhui@cn.ibm.com": {
    username: "xchenhui@cn.ibm.com",
    name: "Chen Hui Xu",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Srini Badari": {
    username: "Srini Badari",
    name: "Srini Badari",
    manager: "Manish Saki",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "dkioshi@ibm.com": {
    username: "dkioshi@ibm.com",
    name: "Daniel Kioshi",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "xinyuwu@us.ibm.com": {
    username: "xinyuwu@us.ibm.com",
    name: "Xinyu Wu",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "marcblec@br.ibm.com": {
    username: "marcblec@br.ibm.com",
    name: "Marcelo Blechner",
    manager: "Leonardo Tekatscz",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "BAKOWSKI@uk.ibm.com": {
    username: "BAKOWSKI@uk.ibm.com",
    name: "Ben Bakowski",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Unnati.Solanki@ibm.com": {
    username: "Unnati.Solanki@ibm.com",
    name: "Unnat Solanki",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "rborto@br.ibm.com": {
    username: "rborto@br.ibm.com",
    name: "Raquel Bortoluci",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Prakruti.Shah@ibm.com": {
    username: "Prakruti.Shah@ibm.com",
    name: "Prakruti Shah",
    manager: "Kadambari Das",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "ecliff@us.ibm.com": {
    username: "ecliff@us.ibm.com",
    name: "Emmet R Clifford",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "psolfa@br.ibm.com": {
    username: "psolfa@br.ibm.com",
    name: "Pedro Solfa Spadacini",
    manager: "Stan Smith",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "LEVELL@uk.ibm.com": {
    username: "LEVELL@uk.ibm.com",
    name: "Jonathan Levell",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "Suraj Tiwari": {
    username: "Suraj Tiwari",
    name: "Suraj Tiwari",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "creyes@us.ibm.com": {
    username: "creyes@us.ibm.com",
    name: "Cesar Reyes",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "MITTENMA@ie.ibm.com": {
    username: "MITTENMA@ie.ibm.com",
    name: "Mark Mitten",
    manager: "Roberta Magueta Costa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "sachin.balagopalan@us.ibm.com": {
    username: "sachin.balagopalan@us.ibm.com",
    name: "Sachin Balagopalan",
    manager: "Marc Dickenson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "bdozorts@us.ibm.com": {
    username: "bdozorts@us.ibm.com",
    name: "Boris Dozortsev",
    manager: "Ricardo de Paula Dias",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "lebm@br.ibm.com": {
    username: "lebm@br.ibm.com",
    name: "Leandro Barollo Borges de Macedo",
    manager: "Kevin Doust",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "abhattacharyya@us.ibm.com": {
    username: "abhattacharyya@us.ibm.com",
    name: "Anamitra Bhattacharyya",
    manager: "Brandon Brockway",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "jennyw@us.ibm.com": {
    username: "jennyw@us.ibm.com",
    name: "Jenny Wang",
    manager: "Brandon Brockway",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "mcaissey@us.ibm.com": {
    username: "mcaissey@us.ibm.com",
    name: "Marcia R Caissey",
    manager: "Katherine Emerson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "msielian@us.ibm.com": {
    username: "msielian@us.ibm.com",
    name: "Michael Sielian",
    manager: "Katherine Emerson",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "peter_niblett@uk.ibm.com": {
    username: "peter_niblett@uk.ibm.com",
    name: "Peter Niblett",
    manager: "Brandon Brockway",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "sls@ca.ibm.com": {
    username: "sls@ca.ibm.com",
    name: "Sean Stuckless",
    manager: "Brandon Brockway",
    ismanager: false,
    isadmin: true,
    daysallowed: { vacation: 0, personal: 0 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "abpaul24@in.ibm.com": {
    username: "abpaul24@in.ibm.com",
    name: "Abhishek Paul",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 25, personal: 4 },
    preferences: { theme: "light", hovertoflip: true, yearlayout: "3:4" },
  },
  "tom.rontiris@us.ibm.com": {
    username: "tom.rontiris@us.ibm.com",
    name: "Tom Rontiris",
    manager: "Brian Ragusa",
    ismanager: false,
    isadmin: false,
    daysallowed: { vacation: 25, personal: 4 },
    preferences: {
      theme: "light",
      hovertoflip: true,
      yearlayout: "3:4",
      mask: true,
      defaulttab: "organization",
    },
  },
};

module.exports = { teamsFromDB, usersFromDB, usersTimeOffDataFromDB };
