
//empty team 
// {
//   members: [],
//   owner: ''
// }


export const teamsFromDB = {
  'ragusa-reports' : {
    members: [
    'trontiris','jakkireddi','togden','ageller','centerline','ksirvent','kfernandes','mchintagunta',
    'rchauda','achauhan','apaul','amirza','vbhatra','ctejos','hdavis'
    ],
    owner: 'bragusa'
  },
  'emerson-reports': {
    owner: 'kemerson',
    members: [
      'bragusa', 'ltekatscz', 'mdickenson', 'rdias', 'shauptman','yzheng'
    ]
  },
  'crispin-reports': {
    owner: 'mcrispin',
    members: [
      'malgazaz', 'kdas', 'kdoust', 'slai', 'rcosta', 'tolson', 'msaki',
    ]
  },
  'brockway-managers' :{
    owner: 'bbrockway',
    members: ['kemerson','mcrispin','kdas','bragusa','ltekatscz','mdickenson','rcosta','kdoust','rdias','msaki']
  },
  'brockway-reports' :{
    owner: 'bbrockway',
    members: ['jwang','kemerson', 'mcaissey', 'msielian','pniblett','sstuckless','abhattacharyya','mcrispin']
  },
  'das-reports' :{
    owner: 'kdas',
    members: ['aquinteiro','amangalvedkar','aadawadkar','amarcelino','anarayanan','amahawal','asalah',
    'cazadze','nshivashankaraiah','pkosalaram','pkim','racree','svalluri','ssyed']
  },
  'tekatscz-reports' :{
    owner: 'ltekatscz',
    members: ['bzhu','ckao','eklingelberger','hpalleti','jnunes','lsreedhara','mblechner','maraujo','mmedeiros','tquinn','thart']
  },
  'doust-reports' :{
    owner: 'kdoust',
    members: ['bcastro','cxu','eclifford','jlu','jluckett','jlevell','lmacedo','rbortoluci','sprabhakar','stiwari','tmao']
  },
  'saki-reports' :{
    owner: 'msaki',
    members: ['cjenkins','kkenge','sbadari','swingate','sbube','vkumar','yyadav']
  },
  'dickenson-reports' :{
    owner: 'mdickenson',
    members: ['ahalbeisen','asilva','awhitfield','asrivastev','bbakowski','ccochran','distrate','dparker',
    'ebarros','iboden','ldavidson','pstone','rresul','sbalagopalan','sbudhiraja','tklapiscak','vpatel']
  },
  'dias-reports' :{
    owner: 'rdias',
    members: ['awills','amccafferty','ashah','amhashelkar','bdozortsev','bgarrett','creyes','cvukovic','jgydus',
    'phalbeisen','pshah','rchaudhary','sboudreau','smishra','usolanki','xwu']
  },
  'costa-reports' :{
    owner: 'rcosta',
    members: ['athakur','aferreira','dkioshi','dlopes','fbergamo','inietmann','iandrei','jgonçalves','lyoshida',
    'lsilva','llucena','mmitten','mraikhline','naraujo','plin','qmao','svelagapudi','ycasanova','yjia']
  },
  'others' :{
    owner: 'bragusa',
    members: ['adonatelli','yzhu','elibow','pspadacini','achiavegatto']
  }
};

//empty user data 
// { username: '', 
//   years: {
//     "2023":{
//       timeoff:{},
//       totals:{
//         vacation:0,
//         personal:0
//       }
//     }
//   }
// }

const old_usersTimeOffDataFromDB = [
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"pkosalaram"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":30,"personal":0}}},"username":"sbudhiraja"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"fbergamo"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"slai"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"togden"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":3}}},"username":"ksirvent"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"cvukovic"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"phalbeisen"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"shauptman"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"yzhu"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"distrate"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"awills"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"smishra"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"yjia"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"svelagapudi"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"amangalvedkar"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"aquinteiro"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"athakur"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"aadawadkar"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"yyadav"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"pkim"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"dparker"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"amirza"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"lyoshida"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"inietmann"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"kfernandes"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"ebarros"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"vkumar"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"vpatel"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ashah"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"achauhan"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":15,"personal":4}}},"username":"awhitfield"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"elibow"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"naraujo"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"adonatelli"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jgydus"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":26,"personal":0}}},"username":"amahawal"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jakkireddi"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"amarcelino"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sboudreau"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"asalah"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":20,"personal":0}}},"username":"nshivashankaraiah"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":30,"personal":0}}},"username":"ldavison"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"aferreira"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sprabhakar"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ccochran"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"dlopes"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"iandrei"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"svalluri"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ycasanova"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"mchintagunta"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"asilva"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"achiavegatto"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sbube"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"tolson"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ssyed"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"amccafferty"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"centerline"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jgonçalves"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"kkenge"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"asrivastev"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"rchauda"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"rchaudhary"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"plin"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":1}}},"username":"anarayanan"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"ageller"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"hpalleti"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"ctejos"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mmedeiros"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"eklingelberger"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"llucena"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"lsilva"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"qmao"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"hdavis"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"thart"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"cazadze"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"cjenkins"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"vbhatra"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"tklapiscak"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bgarrett"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bzhu"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"racree"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jnunes"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"iboden"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"tquinn"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ckao"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"malgazaz"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mraikhline"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"yzheng"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"swingate"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"lsreedhara"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"amhashelkar"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"jlu"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"rresul"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bcastro"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"pstone"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jluckett"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":30,"personal":0}}},"username":"tmao"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"maraujo"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"cxu"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sbadari"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"dkioshi"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"xwu"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mblechner"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"bbakowski"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"usolanki"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"rbortoluci"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"pshah"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"eclifford"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"pspadacini"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jlevell"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"stiwari"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"creyes"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mmitten"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sbalagopalan"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bdozortsev"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"lmacedo"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"abhattacharyya"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jwang"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"mcaissey"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"msielian"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"pniblett"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":3}}},"username":"sstuckless"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"apaul"},
{"years":{"2023":{"comments": {"11-22":"this is a test comment","11-23":"this is another a test comment"}, "timeoff":{"1-2":"H","1-16":"H","1-27":"P","3-17":"P","3-20":"P","4-24":"V","5-24":"V","5-29":"H","6-5":"VP","6-6":"VA","6-16":"V","7-3":"V","7-4":"H","7-27":"V","7-28":"V","7-31":"V","8-4":"V","8-21":"V","8-22":"V","8-23":"V","8-24":"V","8-25":"P","8-28":"V","9-4":"H","10-11":"S","10-12":"S","10-13":"S","10-16":"S","11-22":"V","11-23":"H","11-24":"H","12-25":"H"},"totals":{"vacation":25,"personal":4}}}, "username":"mcrispin"},
{"years":{"2023":{"comments": {'2-28':'Colonoscopy', '5-26': 'Early Memorial Day (Afternoon)'}, "timeoff":{'2-23':'VP','2-28':'O','3-6':'P','3-20':'VP','3-23':'P','3-24':'P','3-27':'P','3-28':'V','5-8':'V','5-9':'V','5-10':'V','5-11':'V','5-12':'V','5-26':'O','6-21':'V','7-3':'V','7-14':'V','7-17':'V','7-18':'V','7-19':'V','7-20':'V','7-21':'V','11-10':'V','11-22':'V','11-23':'H','11-24':'H','12-20':'V','12-21':'V','12-22':'V','12-25':'H','12-26':'V','12-27':'V','12-28':'V','12-29':'V'},"totals":{"vacation":0,"personal":0}}},"username":"trontiris"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"kdas"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}}, "username":"kemerson"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"bbrockway"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"kdoust"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"rcosta"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"ltekatscz"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"bragusa"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":15,"personal":4}}}, "username":"rdias"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"mdickenson"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}}, "username":"msaki"}

];


export const usersTimeOffDataFromDB = [
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"pakosal1@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":30,"personal":0}}},"username":"sbudhira@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"febergamo@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"slai@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"ogdent@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":3}}},"username":"Kaila.Lopez-Sirvent@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"rodas@ca.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"pete.halbeisen@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"shauptma@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"yinzhu@ca.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"Daniel.Istrate1@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"awills@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Subrat Mishra"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jiayybj@cn.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Sujala.Velagapudi@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"amitmangalvedkar@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"alexandre.quinteiro@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"athakur@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"aadawadk@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"YASH.YADAV@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ypkim@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"PARKERDA@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"aqib.mirza@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"lyoshida@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"igortn@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"kristinf@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"elyb@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Vinit.Kumar3@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"Vishal.Patel7@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ankits@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Anjali.Chauhan2@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":15,"personal":4}}},"username":"WHITFIEA@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"elibow@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"naraujos@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"alex.donatelli@it.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jgydus@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":26,"personal":0}}},"username":"Ashish.Mahawal1@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bakkired@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"andrercm@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sboudrea@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"abensal@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":20,"personal":0}}},"username":"nataraj.s@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":30,"personal":0}}},"username":"Leo.Davison@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"andrefgj@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sanjay.prabhakar@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"cochran@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"danilol@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"IANDREI2@ie.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"svalluri@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"yann.casanova@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"meshack.chintagunta@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"anahas@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"arlindo@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"SBUBE@de.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"tessa.olson@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"shajsyed@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mccafferty@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"enterlin@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jeancrg@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Kunal.Kenge@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Atul.Srivastav@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Rohit.Chauda@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Rajan Chaudhary"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"PANPANLI@ie.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":1}}},"username":"Arun.Narayanan2@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"Ari.Geller@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Hari.Palleti@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"cgirani@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Matheus.Cardoso@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Eric Klingelberger"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"luiz.lucena@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"luisfelipe@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"qmao@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"hectord@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"twhart@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"caroazadze@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Claire.Jenkins@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"vbhatra@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"KLAPITOM@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"briangar@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bzhu@ca.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"acree@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"karolsn@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"IANBODEN@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"quinnt@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ckao@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mlalgaza@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mraikhli@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"zhengy@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"swingate@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"lokesh.sreedhara@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ashlesha.potdar@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"luje@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Rawa.Resul@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"beatriz.castro@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"STONEPD@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Jonah.Luckett@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":30,"personal":0}}},"username":"maotsh@cn.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"marcof@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"xchenhui@cn.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Srini Badari"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"dkioshi@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":0}}},"username":"xinyuwu@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"marcblec@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":22,"personal":0}}},"username":"BAKOWSKI@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"Unnati.Solanki@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"rborto@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"Prakruti.Shah@ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ecliff@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"psolfa@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"LEVELL@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"Suraj Tiwari"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"creyes@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"MITTENMA@ie.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"sachin.balagopalan@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bdozorts@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"lebm@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"abhattacharyya@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"jennyw@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"mcaissey@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"msielian@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"peter_niblett@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":3}}},"username":"sls@ca.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"abpaul24@in.ibm.com"},
{"years":{"2023":{"comments":{"11-22":"this is a test comment","11-23":"this is another a test comment"},"timeoff":{"1-2":"H","1-16":"H","1-27":"P","3-17":"P","3-20":"P","4-24":"V","5-24":"V","5-29":"H","6-5":"VP","6-6":"VA","6-16":"V","7-3":"V","7-4":"H","7-27":"V","7-28":"V","7-31":"V","8-4":"V","8-21":"V","8-22":"V","8-23":"V","8-24":"V","8-25":"P","8-28":"V","9-4":"H","10-11":"S","10-12":"S","10-13":"S","10-16":"S","11-22":"V","11-23":"H","11-24":"H","12-25":"H"},"totals":{"vacation":25,"personal":4}}},"username":"mcrispin@us.ibm.com"},
{"years":{"2023":{"comments":{"2-28":"Colonoscopy","5-26":"Early Memorial Day (Afternoon)"},"timeoff":{"2-23":"VP","2-28":"O","3-6":"P","3-20":"VP","3-23":"P","3-24":"P","3-27":"P","3-28":"V","5-8":"V","5-9":"V","5-10":"V","5-11":"V","5-12":"V","5-26":"O","6-21":"V","7-3":"V","7-14":"V","7-17":"V","7-18":"V","7-19":"V","7-20":"V","7-21":"V","11-10":"V","11-22":"V","11-23":"H","11-24":"H","12-20":"V","12-21":"V","12-22":"V","12-25":"H","12-26":"V","12-27":"V","12-28":"V","12-29":"V"},"totals":{"vacation":0,"personal":0}}},"username":"tom.rontiris@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"kadamdas@in.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":25,"personal":4}}},"username":"kemerson@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"brockway@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"kevin_doust@uk.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"roberta.magueta@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"ltekatsc@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bragusa@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":15,"personal":4}}},"username":"rpdias@br.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"mdickens@us.ibm.com"},
{"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"manishsaki@in.ibm.com"}
];



// empty user info
// { username:'',
//   name:'',
//   isadmin: true, 
//   manager:"Brian Ragusa",
//   daysallowed:{
//     vacation:25,
//     personal:4
//   },
//   preferences:{
//     theme:"light",
//     hovertoflip:true,
//     yearlayout:"3:4",
//     mask: true,
//     defaulttab:'organization'
//   }
// }

// const old_usersFromDB = {
//   mdickenson:{email:"mdickens@us.ibm.com",username:"mdickenson",name:"Marc Dickenson",manager:"Katherine Emerson",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   kdas:{email:"kadamdas@in.ibm.com",username:"kdas",name:"Kadambari Das",manager:"Michael Crispin",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   rcosta:{email:"roberta.magueta@br.ibm.com",username:"rcosta",name:"Roberta Magueta Costa",manager:"Michael Crispin",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   mcrispin:{email:"mcrispin@us.ibm.com",username:"mcrispin",name:"Michael Crispin",manager:"Brandon Brockway",ismanager: true ,daysallowed:{vacation:25,personal:4},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4",mask: true, defaultteams: ['crispin-reports']}},
//   kemerson:{email:"kemerson@us.ibm.com",username:"kemerson",name:"Katherine Emerson",manager:"Brandon Brockway",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   bbrockway:{email:"brockway@us.ibm.com",username:"bbrockway",name:"Brandon Brockway",manager:"Suzanne Livingston",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   kdoust:{email:"kevin_doust@uk.ibm.com",username:"kdoust",name:"Kevin Doust",manager:"Michael Crispin",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ltekatscz:{email:"ltekatsc@br.ibm.com",username:"ltekatscz",name:"Leonardo Tekatscz",manager:"Katherine Emerson",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   bragusa:{email:"bragusa@us.ibm.com",username:"bragusa",name:"Brian Ragusa",manager:"Katherine Emerson",isadmin: true, ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4", defaultteams: ['ragusa-reports']  }},
//   msaki:{email:"manishsaki@in.ibm.com",username:"msaki",name:"Manish Saki",manager:"Michael Crispin",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   rdias:{email:"rpdias@br.ibm.com",username:"rdias",name:"Ricardo de Paula Dias",manager:"Katherine Emerson",ismanager: true ,daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   pkosalaram:{email:"pakosal1@in.ibm.com",username:"pkosalaram",name:"Padmanabhan Kosalaram",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   sbudhiraja:{email:"sbudhira@us.ibm.com",username:"sbudhiraja",name:"Sarika Budhiraja",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   fbergamo:{email:"febergamo@ibm.com",username:"fbergamo",name:"Fernanda Bergamo",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   slai:{email:"slai@us.ibm.com",username:"slai",name:"Su-Kuei Lai",manager:"Michael Crispin",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   togden:{email:"ogdent@us.ibm.com",username:"togden",name:"Thomas Ogden",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ksirvent:{email:"Kaila.Lopez-Sirvent@ibm.com",username:"ksirvent",name:"Kaila Sirvent",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   cvukovic:{email:"rodas@ca.ibm.com",username:"cvukovic",name:"Clarissa Vukovic",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   phalbeisen:{email:"pete.halbeisen@us.ibm.com",username:"phalbeisen",name:"Pete Halbeisen",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   shauptman:{email:"shauptma@us.ibm.com",username:"shauptman",name:"Steve Hauptman",manager:"Katherine Emerson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   yzhu:{email:"yinzhu@ca.ibm.com",username:"yzhu",name:"Yin Zhu",manager:"Ana Villarreal",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   distrate:{email:"Daniel.Istrate1@ibm.com",username:"distrate",name:"Daniel Istrate",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   awills:{email:"awills@us.ibm.com",username:"awills",name:"Andrea Wills",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   smishra:{email:"Subrat Mishra",username:"smishra",name:"Subrat Mishra",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   yjia:{email:"jiayybj@cn.ibm.com",username:"yjia",name:"Yuan Yuan Jia",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   svelagapudi:{email:"Sujala.Velagapudi@ibm.com",username:"svelagapudi",name:"Sujala Velagapudi",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   amangalvedkar:{email:"amitmangalvedkar@in.ibm.com",username:"amangalvedkar",name:"Amit Mangalvedkar",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},  
//   aquinteiro:{email:"alexandre.quinteiro@br.ibm.com",username:"aquinteiro",name:"Alexandre Fernandes Quinteiro",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   athakur:{email:"athakur@us.ibm.com",username:"athakur",name:"Aman Thakur",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   aadawadkar:{email:"aadawadk@in.ibm.com",username:"aadawadkar",name:"Amrin Maria R. Khan Adawadkar",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   yyadav:{email:"YASH.YADAV@ibm.com",username:"yyadav",name:"Yash Yadav",manager:"Manish Saki",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   pkim:{email:"ypkim@us.ibm.com",username:"pkim",name:"Phil Kim",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   dparker:{email:"PARKERDA@uk.ibm.com",username:"dparker",name:"David Parker",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   amirza:{email:"aqib.mirza@ibm.com",username:"amirza",name:"Aqib Mirza",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   lyoshida:{email:"lyoshida@br.ibm.com",username:"lyoshida",name:"Leandro Yoshida",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   inietmann:{email:"igortn@ibm.com",username:"inietmann",name:"Igor Nietmann",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   kfernandes:{email:"kristinf@us.ibm.com",username:"kfernandes",name:"Kristin M Fernandes",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ebarros:{email:"elyb@br.ibm.com",username:"ebarros",name:"Ely De Azevedo Barros",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   vkumar:{email:"Vinit.Kumar3@ibm.com",username:"vkumar",name:"Vinit Kumar",manager:"Manish Saki",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   vpatel:{email:"Vishal.Patel7@ibm.com",username:"vpatel",name:"Vishal Patel",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ashah:{email:"ankits@ibm.com",username:"ashah",name:"Ankit Shah",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   achauhan:{email:"Anjali.Chauhan2@ibm.com",username:"achauhan",name:"Anjali Chauhan",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   awhitfield:{email:"WHITFIEA@uk.ibm.com",username:"awhitfield",name:"Andrew Whitfield",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   elibow:{email:"elibow@us.ibm.com",username:"elibow",name:"Eric B. Libow",manager:"Suzanne Livingston",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   naraujo:{email:"naraujos@br.ibm.com",username:"naraujo",name:"Natalia Araujo",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   adonatelli:{email:"alex.donatelli@it.ibm.com",username:"adonatelli",name:"Alex Donatelli",manager:"Suzanne Livingston",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jgydus:{email:"jgydus@us.ibm.com",username:"jgydus",name:"Joseph Gydus",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   amahawal:{email:"Ashish.Mahawal1@ibm.com",username:"amahawal",name:"Ashish Mahawal",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jakkireddi:{email:"bakkired@in.ibm.com",username:"jakkireddi",name:"Jaanvi Akkireddi",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   amarcelino:{email:"andrercm@br.ibm.com",username:"amarcelino",name:"Andre Ricardo De Campos Marcelino",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   sboudreau:{email:"sboudrea@us.ibm.com",username:"sboudreau",name:"Scott Boudreau",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   asalah:{email:"abensal@us.ibm.com",username:"asalah",name:"Aymen Ben Salah",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   nshivashankaraiah:{email:"nataraj.s@in.ibm.com",username:"nshivashankaraiah",name:"Nataraj Shivashankaraiah",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ldavison:{email:"Leo.Davison@uk.ibm.com",username:"ldavison",name:"Leo Davison",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   aferreira:{email:"andrefgj@br.ibm.com",username:"aferreira",name:"Andre Ferreira",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   sprabhakar:{email:"sanjay.prabhakar@uk.ibm.com",username:"sprabhakar",name:"Sanjay Prabhakar",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ccochran:{email:"cochran@ibm.com",username:"ccochran",name:"Christopher Cochran",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   dlopes:{email:"danilol@br.ibm.com",username:"dlopes",name:"Danilo Lopes",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   iandrei:{email:"IANDREI2@ie.ibm.com",username:"iandrei",name:"Ionut Andrei",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   svalluri:{email:"svalluri@in.ibm.com",username:"svalluri",name:"Sekhar Valluri",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ycasanova:{email:"yann.casanova@ibm.com",username:"ycasanova",name:"Yann Casanova",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   mchintagunta:{email:"meshack.chintagunta@in.ibm.com",username:"mchintagunta",name:"Meshack Chintagunta",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   asilva:{email:"anahas@br.ibm.com",username:"asilva",name:"Alice Nahas da Silva",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   achiavegatto:{email:"arlindo@us.ibm.com",username:"achiavegatto",name:"Arlindo Chiavegatto",manager:"Brandon Brockway",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   sbube:{email:"SBUBE@de.ibm.com",username:"sbube",name:"Sören Bube",manager:"Manish Saki",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   tolson:{email:"tessa.olson@uk.ibm.com",username:"tolson",name:"Tessa Olson",manager:"Michael Crispin",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ssyed:{email:"shajsyed@in.ibm.com",username:"ssyed",name:"Shajeena Syed",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   amccafferty:{email:"mccafferty@us.ibm.com",username:"amccafferty",name:"Angela McCafferty",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   centerline:{email:"enterlin@us.ibm.com",username:"centerline",name:"Christy Enterline",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jgonçalves:{email:"jeancrg@br.ibm.com",username:"jgonçalves",name:"Jean Gonçalves",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   kkenge:{email:"Kunal.Kenge@ibm.com",username:"kkenge",name:"Kunal Kenge",manager:"Manish Saki",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   asrivastev:{email:"Atul.Srivastav@ibm.com",username:"asrivastev",name:"Atul Srivastev",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   rchauda:{email:"Rohit.Chauda@ibm.com",username:"rchauda",name:"Rohit Chauda",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   rchaudhary:{email:"Rajan Chaudhary",username:"rchaudhary",name:"Rajan Chaudhary",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   plin:{email:"PANPANLI@ie.ibm.com",username:"plin",name:"Panpan Lin",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   anarayanan:{email:"Arun.Narayanan2@ibm.com",username:"anarayanan",name:"Arun Narayanan",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ageller:{email:"Ari.Geller@ibm.com",username:"ageller",name:"Ari Geller",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   hpalleti:{email:"Hari.Palleti@ibm.com",username:"hpalleti",name:"Hari Palleti",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ctejos:{email:"cgirani@br.ibm.com",username:"ctejos",name:"Claudia Regina Girani Tejos",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   mmedeiros:{email:"Matheus.Cardoso@ibm.com",username:"mmedeiros",name:"Matheus Cardoso de Medeiros",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   eklingelberger:{email:"Eric Klingelberger",username:"eklingelberger",name:"Eric Klingelberger",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   llucena:{email:"luiz.lucena@ibm.com",username:"llucena",name:"Luiz Gustavo Lucena",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   lsilva:{email:"luisfelipe@ibm.com",username:"lsilva",name:"Luis Silva",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   qmao:{email:"qmao@us.ibm.com",username:"qmao",name:"Qiuping Mao",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   hdavis:{email:"hectord@br.ibm.com",username:"hdavis",name:"Hector Davis",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   thart:{email:"twhart@us.ibm.com",username:"thart",name:"Tremaine Hart",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   cazadze:{email:"caroazadze@ibm.com",username:"cazadze",name:"Caroline E Azadze",manager:"marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   cjenkins:{email:"Claire.Jenkins@ibm.com",username:"cjenkins",name:"Claire Jenkins",manager:"Manish Saki",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   vbhatra:{email:"vbhatra@us.ibm.com",username:"vbhatra",name:"Vidad Bhatra",manager:"Brian Ragusa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   tklapiscak:{email:"KLAPITOM@uk.ibm.com",username:"tklapiscak",name:"Tom Klapiscak",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   bgarrett:{email:"briangar@us.ibm.com",username:"bgarrett",name:"Brian Garrett",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   bzhu:{email:"bzhu@ca.ibm.com",username:"bzhu",name:"Brian Zhu",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   racree:{email:"acree@us.ibm.com",username:"racree",name:"Rick Acree",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jnunes:{email:"karolsn@br.ibm.com",username:"jnunes",name:"Joao Paulo Karol Santos Nunes",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   iboden:{email:"IANBODEN@uk.ibm.com",username:"iboden",name:"Ian Boden",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   tquinn:{email:"quinnt@us.ibm.com",username:"tquinn",name:"Terence J. Quinn",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   ckao:{email:"ckao@us.ibm.com",username:"ckao",name:"Conrad Kao",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   malgazaz:{email:"mlalgaza@us.ibm.com",username:"malgazaz",name:"Magdy Labib Al-Gazaz",manager:"Michael Crispin",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   mraikhline:{email:"mraikhli@us.ibm.com",username:"mraikhline",name:"Mikhail Raikhline",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   yzheng:{email:"zhengy@us.ibm.com",username:"yzheng",name:"Yajin Zheng",manager:"Katherine Emerson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   swingate:{email:"swingate@ibm.com",username:"swingate",name:"Steven Wingate",manager:"Manish Saki",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   lsreedhara:{email:"lokesh.sreedhara@us.ibm.com",username:"lsreedhara",name:"Lokesh Sreedhara",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   amhashelkar:{email:"ashlesha.potdar@in.ibm.com",username:"amhashelkar",name:"Ashlesha Mhashelkar",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jlu:{email:"luje@us.ibm.com",username:"jlu",name:"Jennifer Lu",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   rresul:{email:"Rawa.Resul@ibm.com",username:"rresul",name:"Rawa Resul",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   bcastro:{email:"beatriz.castro@ibm.com",username:"bcastro",name:"Beatriz Falcão Castro",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   pstone:{email:"STONEPD@uk.ibm.com",username:"pstone",name:"Paul Stone",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jluckett:{email:"Jonah.Luckett@ibm.com",username:"jluckett",name:"Jonah Luckett",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   tmao:{email:"maotsh@cn.ibm.com",username:"tmao",name:"Ting Mao",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   maraujo:{email:"marcof@br.ibm.com",username:"maraujo",name:"Marco Antonio Ferreira De Araujo",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   cxu:{email:"xchenhui@cn.ibm.com",username:"cxu",name:"Chen Hui Xu",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   sbadari:{email:"Srini Badari",username:"sbadari",name:"Srini Badari",manager:"Manish Saki",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   dkioshi:{email:"dkioshi@ibm.com",username:"dkioshi",name:"Daniel Kioshi",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   xwu:{email:"xinyuwu@us.ibm.com",username:"xwu",name:"Xinyu Wu",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   mblechner:{email:"marcblec@br.ibm.com",username:"mblechner",name:"Marcelo Blechner",manager:"Leonardo Tekatscz",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   bbakowski:{email:"BAKOWSKI@uk.ibm.com",username:"bbakowski",name:"Ben Bakowski",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   usolanki:{email:"Unnati.Solanki@ibm.com",username:"usolanki",name:"Unnat Solanki",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   rbortoluci:{email:"rborto@br.ibm.com",username:"rbortoluci",name:"Raquel Bortoluci",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   pshah:{email:"Prakruti.Shah@ibm.com",username:"pshah",name:"Prakruti Shah",manager:"Kadambari Das",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   eclifford:{email:"ecliff@us.ibm.com",username:"eclifford",name:"Emmet R Clifford",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   pspadacini:{email:"psolfa@br.ibm.com",username:"pspadacini",name:"Pedro Solfa Spadacini",manager:"Stan Smith",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jlevell:{email:"LEVELL@uk.ibm.com",username:"jlevell",name:"Jonathan Levell",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   stiwari:{email:"Suraj Tiwari",username:"stiwari",name:"Suraj Tiwari",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   creyes:{email:"creyes@us.ibm.com",username:"creyes",name:"Cesar Reyes",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   mmitten:{email:"MITTENMA@ie.ibm.com",username:"mmitten",name:"Mark Mitten",manager:"Roberta Magueta Costa",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   sbalagopalan:{email:"sachin.balagopalan@us.ibm.com",username:"sbalagopalan",name:"Sachin Balagopalan",manager:"Marc Dickenson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   bdozortsev:{email:"bdozorts@us.ibm.com",username:"bdozortsev",name:"Boris Dozortsev",manager:"Ricardo de Paula Dias",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   lmacedo:{email:"lebm@br.ibm.com",username:"lmacedo",name:"Leandro Barollo Borges de Macedo",manager:"Kevin Doust",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   abhattacharyya:{email:"abhattacharyya@us.ibm.com",username:"abhattacharyya",name:"Anamitra Bhattacharyya",manager:"Brandon Brockway",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   jwang:{email:"jennyw@us.ibm.com",username:"jwang",name:"Jenny Wang",manager:"Brandon Brockway",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   mcaissey:{email:"mcaissey@us.ibm.com",username:"mcaissey",name:"Marcia R Caissey",manager:"Katherine Emerson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   msielian:{email:"msielian@us.ibm.com",username:"msielian",name:"Michael Sielian",manager:"Katherine Emerson",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   pniblett:{email:"peter_niblett@uk.ibm.com",username:"pniblett",name:"Peter Niblett",manager:"Brandon Brockway",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   sstuckless:{email:"sls@ca.ibm.com",username:"sstuckless",name:"Sean Stuckless",manager:"Brandon Brockway",daysallowed:{vacation:0,personal:0},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4"  }},
//   apaul:{email:"abpaul24@in.ibm.com",username:"apaul",name:"Abhishek Paul",manager:"Brian Ragusa",daysallowed:{vacation:25,personal:4},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4" }},
//   trontiris:{email:"tom.rontiris@us.ibm.com",username:"trontiris",name:"Tom Rontiris",isadmin: true, manager:"Brian Ragusa",daysallowed:{vacation:25,personal:4},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4",mask: true, defaulttab: 'month' }}
// };






export const usersFromDB = {
"mdickens@us.ibm.com":{"username":"mdickens@us.ibm.com","name":"Marc Dickenson","manager":"Katherine Emerson","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"kadamdas@in.ibm.com":{"username":"kadamdas@in.ibm.com","name":"Kadambari Das","manager":"Michael Crispin","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"roberta.magueta@br.ibm.com":{"username":"roberta.magueta@br.ibm.com","name":"Roberta Magueta Costa","manager":"Michael Crispin","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"mcrispin@us.ibm.com":{"username":"mcrispin@us.ibm.com","name":"Michael Crispin","manager":"Brandon Brockway","ismanager":true,"daysallowed":{"vacation":25,"personal":4},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4","mask":true,"defaultteams":["crispin-reports"]}},
"kemerson@us.ibm.com":{"username":"kemerson@us.ibm.com","name":"Katherine Emerson","manager":"Brandon Brockway","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"brockway@us.ibm.com":{"username":"brockway@us.ibm.com","name":"Brandon Brockway","manager":"Suzanne Livingston","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"kevin_doust@uk.ibm.com":{"username":"kevin_doust@uk.ibm.com","name":"Kevin Doust","manager":"Michael Crispin","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"ltekatsc@br.ibm.com":{"username":"ltekatsc@br.ibm.com","name":"Leonardo Tekatscz","manager":"Katherine Emerson","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"bragusa@us.ibm.com":{"username":"bragusa@us.ibm.com","name":"Brian Ragusa","manager":"Katherine Emerson","isadmin":true,"ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4","defaultteams":["ragusa-reports"]}},
"manishsaki@in.ibm.com":{"username":"manishsaki@in.ibm.com","name":"Manish Saki","manager":"Michael Crispin","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"rpdias@br.ibm.com":{"username":"rpdias@br.ibm.com","name":"Ricardo de Paula Dias","manager":"Katherine Emerson","ismanager":true,"daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"pakosal1@in.ibm.com":{"username":"pakosal1@in.ibm.com","name":"Padmanabhan Kosalaram","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"sbudhira@us.ibm.com":{"username":"sbudhira@us.ibm.com","name":"Sarika Budhiraja","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"febergamo@ibm.com":{"username":"febergamo@ibm.com","name":"Fernanda Bergamo","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"slai@us.ibm.com":{"username":"slai@us.ibm.com","name":"Su-Kuei Lai","manager":"Michael Crispin","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"ogdent@us.ibm.com":{"username":"ogdent@us.ibm.com","name":"Thomas Ogden","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Kaila.Lopez-Sirvent@ibm.com":{"username":"Kaila.Lopez-Sirvent@ibm.com","name":"Kaila Sirvent","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"rodas@ca.ibm.com":{"username":"rodas@ca.ibm.com","name":"Clarissa Vukovic","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"pete.halbeisen@us.ibm.com":{"username":"pete.halbeisen@us.ibm.com","name":"Pete Halbeisen","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"shauptma@us.ibm.com":{"username":"shauptma@us.ibm.com","name":"Steve Hauptman","manager":"Katherine Emerson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"yinzhu@ca.ibm.com":{"username":"yinzhu@ca.ibm.com","name":"Yin Zhu","manager":"Ana Villarreal","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Daniel.Istrate1@ibm.com":{"username":"Daniel.Istrate1@ibm.com","name":"Daniel Istrate","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"awills@us.ibm.com":{"username":"awills@us.ibm.com","name":"Andrea Wills","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Subrat Mishra":{"username":"Subrat Mishra","name":"Subrat Mishra","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"jiayybj@cn.ibm.com":{"username":"jiayybj@cn.ibm.com","name":"Yuan Yuan Jia","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Sujala.Velagapudi@ibm.com":{"username":"Sujala.Velagapudi@ibm.com","name":"Sujala Velagapudi","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"amitmangalvedkar@in.ibm.com":{"username":"amitmangalvedkar@in.ibm.com","name":"Amit Mangalvedkar","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"alexandre.quinteiro@br.ibm.com":{"username":"alexandre.quinteiro@br.ibm.com","name":"Alexandre Fernandes Quinteiro","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"athakur@us.ibm.com":{"username":"athakur@us.ibm.com","name":"Aman Thakur","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"aadawadk@in.ibm.com":{"username":"aadawadk@in.ibm.com","name":"Amrin Maria R. Khan Adawadkar","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"YASH.YADAV@ibm.com":{"username":"YASH.YADAV@ibm.com","name":"Yash Yadav","manager":"Manish Saki","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"ypkim@us.ibm.com":{"username":"ypkim@us.ibm.com","name":"Phil Kim","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"PARKERDA@uk.ibm.com":{"username":"PARKERDA@uk.ibm.com","name":"David Parker","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"aqib.mirza@ibm.com":{"username":"aqib.mirza@ibm.com","name":"Aqib Mirza","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"lyoshida@br.ibm.com":{"username":"lyoshida@br.ibm.com","name":"Leandro Yoshida","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"igortn@ibm.com":{"username":"igortn@ibm.com","name":"Igor Nietmann","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"kristinf@us.ibm.com":{"username":"kristinf@us.ibm.com","name":"Kristin M Fernandes","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"elyb@br.ibm.com":{"username":"elyb@br.ibm.com","name":"Ely De Azevedo Barros","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Vinit.Kumar3@ibm.com":{"username":"Vinit.Kumar3@ibm.com","name":"Vinit Kumar","manager":"Manish Saki","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Vishal.Patel7@ibm.com":{"username":"Vishal.Patel7@ibm.com","name":"Vishal Patel","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"ankits@ibm.com":{"username":"ankits@ibm.com","name":"Ankit Shah","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Anjali.Chauhan2@ibm.com":{"username":"Anjali.Chauhan2@ibm.com","name":"Anjali Chauhan","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"WHITFIEA@uk.ibm.com":{"username":"WHITFIEA@uk.ibm.com","name":"Andrew Whitfield","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"elibow@us.ibm.com":{"username":"elibow@us.ibm.com","name":"Eric B. Libow","manager":"Suzanne Livingston","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"naraujos@br.ibm.com":{"username":"naraujos@br.ibm.com","name":"Natalia Araujo","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"alex.donatelli@it.ibm.com":{"username":"alex.donatelli@it.ibm.com","name":"Alex Donatelli","manager":"Suzanne Livingston","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"jgydus@us.ibm.com":{"username":"jgydus@us.ibm.com","name":"Joseph Gydus","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Ashish.Mahawal1@ibm.com":{"username":"Ashish.Mahawal1@ibm.com","name":"Ashish Mahawal","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"bakkired@in.ibm.com":{"username":"bakkired@in.ibm.com","name":"Jaanvi Akkireddi","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"andrercm@br.ibm.com":{"username":"andrercm@br.ibm.com","name":"Andre Ricardo De Campos Marcelino","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"sboudrea@us.ibm.com":{"username":"sboudrea@us.ibm.com","name":"Scott Boudreau","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"abensal@us.ibm.com":{"username":"abensal@us.ibm.com","name":"Aymen Ben Salah","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"nataraj.s@in.ibm.com":{"username":"nataraj.s@in.ibm.com","name":"Nataraj Shivashankaraiah","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Leo.Davison@uk.ibm.com":{"username":"Leo.Davison@uk.ibm.com","name":"Leo Davison","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"andrefgj@br.ibm.com":{"username":"andrefgj@br.ibm.com","name":"Andre Ferreira","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"sanjay.prabhakar@uk.ibm.com":{"username":"sanjay.prabhakar@uk.ibm.com","name":"Sanjay Prabhakar","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"cochran@ibm.com":{"username":"cochran@ibm.com","name":"Christopher Cochran","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"danilol@br.ibm.com":{"username":"danilol@br.ibm.com","name":"Danilo Lopes","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"IANDREI2@ie.ibm.com":{"username":"IANDREI2@ie.ibm.com","name":"Ionut Andrei","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"svalluri@in.ibm.com":{"username":"svalluri@in.ibm.com","name":"Sekhar Valluri","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"yann.casanova@ibm.com":{"username":"yann.casanova@ibm.com","name":"Yann Casanova","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"meshack.chintagunta@in.ibm.com":{"username":"meshack.chintagunta@in.ibm.com","name":"Meshack Chintagunta","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"anahas@br.ibm.com":{"username":"anahas@br.ibm.com","name":"Alice Nahas da Silva","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"arlindo@us.ibm.com":{"username":"arlindo@us.ibm.com","name":"Arlindo Chiavegatto","manager":"Brandon Brockway","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"SBUBE@de.ibm.com":{"username":"SBUBE@de.ibm.com","name":"Sören Bube","manager":"Manish Saki","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"tessa.olson@uk.ibm.com":{"username":"tessa.olson@uk.ibm.com","name":"Tessa Olson","manager":"Michael Crispin","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"shajsyed@in.ibm.com":{"username":"shajsyed@in.ibm.com","name":"Shajeena Syed","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"mccafferty@us.ibm.com":{"username":"mccafferty@us.ibm.com","name":"Angela McCafferty","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"enterlin@us.ibm.com":{"username":"enterlin@us.ibm.com","name":"Christy Enterline","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"jeancrg@br.ibm.com":{"username":"jeancrg@br.ibm.com","name":"Jean Gonçalves","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Kunal.Kenge@ibm.com":{"username":"Kunal.Kenge@ibm.com","name":"Kunal Kenge","manager":"Manish Saki","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Atul.Srivastav@ibm.com":{"username":"Atul.Srivastav@ibm.com","name":"Atul Srivastev","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Rohit.Chauda@ibm.com":{"username":"Rohit.Chauda@ibm.com","name":"Rohit Chauda","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Rajan Chaudhary":{"username":"Rajan Chaudhary","name":"Rajan Chaudhary","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"PANPANLI@ie.ibm.com":{"username":"PANPANLI@ie.ibm.com","name":"Panpan Lin","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Arun.Narayanan2@ibm.com":{"username":"Arun.Narayanan2@ibm.com","name":"Arun Narayanan","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Ari.Geller@ibm.com":{"username":"Ari.Geller@ibm.com","name":"Ari Geller","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Hari.Palleti@ibm.com":{"username":"Hari.Palleti@ibm.com","name":"Hari Palleti","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"cgirani@br.ibm.com":{"username":"cgirani@br.ibm.com","name":"Claudia Regina Girani Tejos","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Matheus.Cardoso@ibm.com":{"username":"Matheus.Cardoso@ibm.com","name":"Matheus Cardoso de Medeiros","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Eric Klingelberger":{"username":"Eric Klingelberger","name":"Eric Klingelberger","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"luiz.lucena@ibm.com":{"username":"luiz.lucena@ibm.com","name":"Luiz Gustavo Lucena","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"luisfelipe@ibm.com":{"username":"luisfelipe@ibm.com","name":"Luis Silva","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"qmao@us.ibm.com":{"username":"qmao@us.ibm.com","name":"Qiuping Mao","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"hectord@br.ibm.com":{"username":"hectord@br.ibm.com","name":"Hector Davis","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"twhart@us.ibm.com":{"username":"twhart@us.ibm.com","name":"Tremaine Hart","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"caroazadze@ibm.com":{"username":"caroazadze@ibm.com","name":"Caroline E Azadze","manager":"marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Claire.Jenkins@ibm.com":{"username":"Claire.Jenkins@ibm.com","name":"Claire Jenkins","manager":"Manish Saki","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"vbhatra@us.ibm.com":{"username":"vbhatra@us.ibm.com","name":"Vidad Bhatra","manager":"Brian Ragusa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"KLAPITOM@uk.ibm.com":{"username":"KLAPITOM@uk.ibm.com","name":"Tom Klapiscak","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"briangar@us.ibm.com":{"username":"briangar@us.ibm.com","name":"Brian Garrett","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"bzhu@ca.ibm.com":{"username":"bzhu@ca.ibm.com","name":"Brian Zhu","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"acree@us.ibm.com":{"username":"acree@us.ibm.com","name":"Rick Acree","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"karolsn@br.ibm.com":{"username":"karolsn@br.ibm.com","name":"Joao Paulo Karol Santos Nunes","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"IANBODEN@uk.ibm.com":{"username":"IANBODEN@uk.ibm.com","name":"Ian Boden","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"quinnt@us.ibm.com":{"username":"quinnt@us.ibm.com","name":"Terence J. Quinn","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"ckao@us.ibm.com":{"username":"ckao@us.ibm.com","name":"Conrad Kao","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"mlalgaza@us.ibm.com":{"username":"mlalgaza@us.ibm.com","name":"Magdy Labib Al-Gazaz","manager":"Michael Crispin","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"mraikhli@us.ibm.com":{"username":"mraikhli@us.ibm.com","name":"Mikhail Raikhline","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"zhengy@us.ibm.com":{"username":"zhengy@us.ibm.com","name":"Yajin Zheng","manager":"Katherine Emerson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"swingate@ibm.com":{"username":"swingate@ibm.com","name":"Steven Wingate","manager":"Manish Saki","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"lokesh.sreedhara@us.ibm.com":{"username":"lokesh.sreedhara@us.ibm.com","name":"Lokesh Sreedhara","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"ashlesha.potdar@in.ibm.com":{"username":"ashlesha.potdar@in.ibm.com","name":"Ashlesha Mhashelkar","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"luje@us.ibm.com":{"username":"luje@us.ibm.com","name":"Jennifer Lu","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Rawa.Resul@ibm.com":{"username":"Rawa.Resul@ibm.com","name":"Rawa Resul","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"beatriz.castro@ibm.com":{"username":"beatriz.castro@ibm.com","name":"Beatriz Falcão Castro","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"STONEPD@uk.ibm.com":{"username":"STONEPD@uk.ibm.com","name":"Paul Stone","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Jonah.Luckett@ibm.com":{"username":"Jonah.Luckett@ibm.com","name":"Jonah Luckett","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"maotsh@cn.ibm.com":{"username":"maotsh@cn.ibm.com","name":"Ting Mao","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"marcof@br.ibm.com":{"username":"marcof@br.ibm.com","name":"Marco Antonio Ferreira De Araujo","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"xchenhui@cn.ibm.com":{"username":"xchenhui@cn.ibm.com","name":"Chen Hui Xu","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Srini Badari":{"username":"Srini Badari","name":"Srini Badari","manager":"Manish Saki","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"dkioshi@ibm.com":{"username":"dkioshi@ibm.com","name":"Daniel Kioshi","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"xinyuwu@us.ibm.com":{"username":"xinyuwu@us.ibm.com","name":"Xinyu Wu","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"marcblec@br.ibm.com":{"username":"marcblec@br.ibm.com","name":"Marcelo Blechner","manager":"Leonardo Tekatscz","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"BAKOWSKI@uk.ibm.com":{"username":"BAKOWSKI@uk.ibm.com","name":"Ben Bakowski","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Unnati.Solanki@ibm.com":{"username":"Unnati.Solanki@ibm.com","name":"Unnat Solanki","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"rborto@br.ibm.com":{"username":"rborto@br.ibm.com","name":"Raquel Bortoluci","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Prakruti.Shah@ibm.com":{"username":"Prakruti.Shah@ibm.com","name":"Prakruti Shah","manager":"Kadambari Das","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"ecliff@us.ibm.com":{"username":"ecliff@us.ibm.com","name":"Emmet R Clifford","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"psolfa@br.ibm.com":{"username":"psolfa@br.ibm.com","name":"Pedro Solfa Spadacini","manager":"Stan Smith","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"LEVELL@uk.ibm.com":{"username":"LEVELL@uk.ibm.com","name":"Jonathan Levell","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"Suraj Tiwari":{"username":"Suraj Tiwari","name":"Suraj Tiwari","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"creyes@us.ibm.com":{"username":"creyes@us.ibm.com","name":"Cesar Reyes","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"MITTENMA@ie.ibm.com":{"username":"MITTENMA@ie.ibm.com","name":"Mark Mitten","manager":"Roberta Magueta Costa","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"sachin.balagopalan@us.ibm.com":{"username":"sachin.balagopalan@us.ibm.com","name":"Sachin Balagopalan","manager":"Marc Dickenson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"bdozorts@us.ibm.com":{"username":"bdozorts@us.ibm.com","name":"Boris Dozortsev","manager":"Ricardo de Paula Dias","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"lebm@br.ibm.com":{"username":"lebm@br.ibm.com","name":"Leandro Barollo Borges de Macedo","manager":"Kevin Doust","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"abhattacharyya@us.ibm.com":{"username":"abhattacharyya@us.ibm.com","name":"Anamitra Bhattacharyya","manager":"Brandon Brockway","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"jennyw@us.ibm.com":{"username":"jennyw@us.ibm.com","name":"Jenny Wang","manager":"Brandon Brockway","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"mcaissey@us.ibm.com":{"username":"mcaissey@us.ibm.com","name":"Marcia R Caissey","manager":"Katherine Emerson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"msielian@us.ibm.com":{"username":"msielian@us.ibm.com","name":"Michael Sielian","manager":"Katherine Emerson","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"peter_niblett@uk.ibm.com":{"username":"peter_niblett@uk.ibm.com","name":"Peter Niblett","manager":"Brandon Brockway","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"sls@ca.ibm.com":{"username":"sls@ca.ibm.com","name":"Sean Stuckless","manager":"Brandon Brockway","daysallowed":{"vacation":0,"personal":0},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"abpaul24@in.ibm.com":{"username":"abpaul24@in.ibm.com","name":"Abhishek Paul","manager":"Brian Ragusa","daysallowed":{"vacation":25,"personal":4},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4"}},
"tom.rontiris@us.ibm.com":{"username":"tom.rontiris@us.ibm.com","name":"Tom Rontiris","isadmin":true,"manager":"Brian Ragusa","daysallowed":{"vacation":25,"personal":4},"preferences":{"theme":"light","hovertoflip":true,"yearlayout":"3:4","mask":true,"defaulttab":"month"}}
}





 
//totals
// {"years":{"2023":{"timeoff":{},"totals":{"vacation":0,"personal":0}}},"username":"bdozortsev"},
//settings
//trontiris:{username:"trontiris",name:"Tom Rontiris",manager:"Brian Ragusa",daysallowed:{vacation:25,personal:4},preferences:{theme:"light",hovertoflip:true,yearlayout:"3:4",mask: true, defaulttab: 'organization' }},